### ISSUE TITLE
Website is badly out of date

### ISSUE THREAD

**Issue by kiplingw** [Nicotine-Plus/nicotine-plus#109]
@Mutnick, if you have access to the website, could you please update it with the latest information from the readme? Ideally the website could be a simple page that's automatically generated from the readme's markdown.

**Comment by mathiascode** [comment]
@eLvErDe hosts the website I believe.

**Comment by kiplingw** [comment]
I would suggest a simple page that is updated via cron to render the markdown in the readme. Unfortunately nothing I can do at my end. Website has not been updated in a very long time.

**Comment by mathiascode** [comment]
A dead simple way would be to just drop a _config.yml file in the main repo, enable Github Pages, and clean up the markdown files a bit. All markdown files would be available on the website, and update automatically whenever they are changed. Example: https://mathiascode.github.io/nicotine-plus/

_config.yml:
```
title: Nicotine+
logo: /files/icons/96x96/nicotine-plus.png
description: A graphical client for the SoulSeek peer-to-peer system
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - files/README
  - img/README
  - plugins/README

theme: jekyll-theme-minimal
```
