### ISSUE TITLE
[Feat] plugin to dynamically change listening port

### ISSUE THREAD

**Issue by minicoz** [nicotine-plus/nicotine-plus#3189]
### Describe the solution you'd like
I use gluetun VPN https://github.com/qdm12/gluetun to create a VPN container stack that then I use a nicotine+ docker container to run my setup through. The gluetun has a dynamic port change whenever it restarts because the upstream VPN dynamically changes the port every time it restarts. I want to see if there is a plugin setting to dynamically update the port number in nicotine+. If there is, then I can use python to contact the gluetun control server API to obtain the dynamic port and then use a nicotine+ plugin to update the nicotins client port and then reconnect based on your latest change.

I just havent found the setting in the pynicotine plugins yet.

Is this possible? 

Thanks

Example Docker-compose setup:

```
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    hostname: gluetunvpn
    container_name: gluetun-nictoine
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000
      - 6060:6080 # nicotine-proper
    volumes:
      - /home/Configs/nicotine/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=
      - SERVER_COUNTRIES='United States'
      - PORT_FORWARD_ONLY=on
      - TZ=America/Los_Angeles
      - UPDATER_PERIOD=24h
      - VPN_PORT_FORWARDING_STATUS_FILE=/gluetun/forwarded_port
    restart: unless-stopped

  nicotine-plus:
    image: ghcr.io/fletchto99/nicotine-plus-docker:latest
    container_name: nicotine-plus
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt:/data/mnt
    restart: unless-stopped
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_started
  
```
