### ISSUE TITLE
Mapped shared folder doesn't show on WebUI, 0 folders found

### ISSUE THREAD

**Issue by funkytrain** [Nicotine-Plus/nicotine-plus#3229]
Nicotine+ version:  latest
Operating System/Distribution: Synology DSM 7.2.

### Describe the bug
Mapped a shared folder in docker compose file but it doesn't appear on the WebUI Nicotine+, even after rescaning shares. The rest of WebUI works as expected (although I noticed from time to time it appears a popup saying "disconnected" and the WebUI is freezed, and I have to refresh page F5 in order to unfreeze it, but I don't know if this issue is related).

### Expected behavior
When mapping a shared folder with files I expected it showed as folders found and shared on Nicotine+.

### Steps to reproduce the bug
1. Map on Docker Compose file the volume containg your shared folder.
2. Deploy the container.
3. Enter the WebUI Nicotine+.

### Additional context
My Docker Compose file:
```
services: 
 nicotineplus-proper:
   image: 'sirjmann92/nicotineplus-proper:latest'
   container_name: nicotine
#  network_mode: "container:YourVPNContainerNameHere" # Comment this line out if you're NOT using a VPN container
   ports: # Comment this line out if you ARE using a VPN container (line above)
     - '6565:6565' # Comment this line out if you ARE using a VPN container (lines above)
     - '2234:2234' # Comment this line out if you ARE using a VPN container (lines above)
#  env_file: .env # Optionally use a .env file to store environment variables and login credentials
   environment:
     - TZ=Europe/Madrid
     - DARKMODE=True
     - LOGIN=******
     - PASSW=*******************
     - PUID=**** # Optional: Default is 1000
     - PGID=**** # Optional: Default is 1000
     - UPNP=False
     - AUTO_CONNECT=True
     - TRAY_ICON=False
     - NOTIFY_FILE=False
     - NOTIFY_FOLDER=False
     - NOTIFY_TITLE=False
     - NOTIFY_PM=False
     - NOTIFY_CHATROOM=False
     - NOTIFY_MENTION=False
#    - WEB_UI_PORT=6565 # for custom webUI port assignment. Should match 'port' env variable or VPN webUI port
   volumes:
     - /volume1/docker/nicotine/dl:/downloads
     - /volume1/RAP:/shared
     - /volume1/docker/nicotine/config:/config # Optional: Save your config persistently
     - /volume1/docker/nicotine/config/data:/data # Optional: Store your logs, database, and history
   restart: unless-stopped
```
Screenshot:
![shared](https://github.com/user-attachments/assets/1957460a-f066-43da-b695-11454d4848b2)
